/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Cursor.xs. Do not edit this file, edit Cursor.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Cursor.xs"
#ifdef __cplusplus
extern "C"{
#endif

#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#ifdef __cplusplus
}
#endif

#include "ppport.h"
#include "plCursor.hpp"

#line 27 "Cursor.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 79 "Cursor.c"

XS(XS_SequoiaDB__Cursor_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Cursor_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "CLASS");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0));
	plCursor *	RETVAL;

	RETVAL = new plCursor();
	ST(0) = sv_newmortal();
   sv_setref_pv(ST(0), CLASS, (void *) RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Cursor_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Cursor_next)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "THIS, sv = NULL");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	sv;
	plCursor *   THIS = (plCursor *) SvIV((SV*) SvRV(ST(0)));

	if (items < 2)
	    sv = NULL;
	else {
	    sv = ST(1);
	}
#line 26 "Cursor.xs"
      XPUSHs (THIS->next(sv)) ;
#line 126 "Cursor.c"
	PUTBACK;
	return;
    }
}


XS(XS_SequoiaDB__Cursor_current); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Cursor_current)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "THIS, sv = NULL");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	sv;
	plCursor *   THIS = (plCursor *) SvIV((SV*) SvRV(ST(0)));

	if (items < 2)
	    sv = NULL;
	else {
	    sv = ST(1);
	}
#line 32 "Cursor.xs"
      XPUSHs (THIS->current(sv)) ;
#line 156 "Cursor.c"
	PUTBACK;
	return;
    }
}


XS(XS_SequoiaDB__Cursor_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Cursor_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	plCursor *   THIS = (plCursor *) SvIV((SV*) SvRV(ST(0)));

	delete THIS;
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_SequoiaDB__Cursor); /* prototype to pass -Wmissing-prototypes */
XS(boot_SequoiaDB__Cursor)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        newXS("SequoiaDB::Cursor::new", XS_SequoiaDB__Cursor_new, file);
        newXS("SequoiaDB::Cursor::next", XS_SequoiaDB__Cursor_next, file);
        newXS("SequoiaDB::Cursor::current", XS_SequoiaDB__Cursor_current, file);
        newXS("SequoiaDB::Cursor::DESTROY", XS_SequoiaDB__Cursor_DESTROY, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

