/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Collection.xs. Do not edit this file, edit Collection.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Collection.xs"
#ifdef __cplusplus
extern "C"{
#endif

#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#ifdef __cplusplus
}
#endif

#include "ppport.h"

#include "plCollection.hpp"
#include "plCursor.hpp"

#line 29 "Collection.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 81 "Collection.c"

XS(XS_SequoiaDB__Collection_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "CLASS");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0));
	plCollection *	RETVAL;

	RETVAL = new plCollection();
	ST(0) = sv_newmortal();
   sv_setref_pv(ST(0), CLASS, (void *) RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_query); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_query)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 8)
       croak_xs_usage(cv,  "THIS, querysv=NULL, selectorsv=NULL, orderbysv=NULL, hintsv=NULL, numToSkip = 0, numToReturn = -1, flag = 0");
    {
	SV *	querysv;
	SV *	selectorsv;
	SV *	orderbysv;
	SV *	hintsv;
	long	numToSkip;
	long	numToReturn;
	int	flag;
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	plCursor *	RETVAL;

	if (items < 2)
	    querysv = NULL;
	else {
	    querysv = ST(1);
	}

	if (items < 3)
	    selectorsv = NULL;
	else {
	    selectorsv = ST(2);
	}

	if (items < 4)
	    orderbysv = NULL;
	else {
	    orderbysv = ST(3);
	}

	if (items < 5)
	    hintsv = NULL;
	else {
	    hintsv = ST(4);
	}

	if (items < 6)
	    numToSkip = 0;
	else {
	    numToSkip = (long)SvIV(ST(5));
	}

	if (items < 7)
	    numToReturn = -1;
	else {
	    numToReturn = (long)SvIV(ST(6));
	}

	if (items < 8)
	    flag = 0;
	else {
	    flag = (int)SvIV(ST(7));
	}

	RETVAL = THIS->query(querysv, selectorsv, orderbysv, hintsv, numToSkip, numToReturn, flag);
	ST(0) = sv_newmortal();
   sv_setref_pv(ST(0), "SequoiaDB::Cursor", (void *) RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_insert); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_insert)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, sv");
    {
	SV *	sv = ST(1);
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	bool	RETVAL;

	RETVAL = THIS->insert(sv);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_bulkInsert); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_bulkInsert)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "THIS, sv, flag = FLG_INSERT_CONTONDUP");
    {
	SV *	sv = ST(1);
	int	flag;
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	bool	RETVAL;

	if (items < 3)
	    flag = FLG_INSERT_CONTONDUP;
	else {
	    flag = (int)SvIV(ST(2));
	}

	RETVAL = THIS->bulkInsert(sv, flag);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_count); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_count)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "THIS, sv = NULL");
    {
	SV *	sv;
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	long	RETVAL;
	dXSTARG;

	if (items < 2)
	    sv = NULL;
	else {
	    sv = ST(1);
	}

	RETVAL = THIS->count(sv);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_getCLName); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_getCLName)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = THIS->getCLName();
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_getCSName); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_getCSName)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = THIS->getCSName();
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_getFullName); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_getFullName)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = THIS->getFullName();
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_createLob); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_createLob)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "THIS, oidStr = NULL");
    {
	const char *	oidStr;
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	plLob *	RETVAL;

	if (items < 2)
	    oidStr = NULL;
	else {
	    oidStr = (const char *)SvPV_nolen(ST(1));
	}

	RETVAL = THIS->createLob(oidStr);
	ST(0) = sv_newmortal();
   sv_setref_pv(ST(0), "SequoiaDB::Lob", (void *) RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_removeLob); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_removeLob)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, oidStr");
    {
	const char *	oidStr = (const char *)SvPV_nolen(ST(1));
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	bool	RETVAL;

	RETVAL = THIS->removeLob(oidStr);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_openLob); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_openLob)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, oidStr");
    {
	const char *	oidStr = (const char *)SvPV_nolen(ST(1));
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	plLob *	RETVAL;

	RETVAL = THIS->openLob(oidStr);
	ST(0) = sv_newmortal();
   sv_setref_pv(ST(0), "SequoiaDB::Lob", (void *) RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_listLobs); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_listLobs)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	plCursor *	RETVAL;

	RETVAL = THIS->listLobs();
	ST(0) = sv_newmortal();
   sv_setref_pv(ST(0), "SequoiaDB::Cursor", (void *) RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_explain); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_explain)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 9)
       croak_xs_usage(cv,  "THIS, conditionsv=NULL, selectorsv=NULL, orderbysv=NULL, hintsv=NULL, numToSkip = 0, numToReturn = -1, flag = 0, optionsv = NULL");
    {
	SV *	conditionsv;
	SV *	selectorsv;
	SV *	orderbysv;
	SV *	hintsv;
	long	numToSkip;
	long	numToReturn;
	int	flag;
	SV *	optionsv;
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	plCursor *	RETVAL;

	if (items < 2)
	    conditionsv = NULL;
	else {
	    conditionsv = ST(1);
	}

	if (items < 3)
	    selectorsv = NULL;
	else {
	    selectorsv = ST(2);
	}

	if (items < 4)
	    orderbysv = NULL;
	else {
	    orderbysv = ST(3);
	}

	if (items < 5)
	    hintsv = NULL;
	else {
	    hintsv = ST(4);
	}

	if (items < 6)
	    numToSkip = 0;
	else {
	    numToSkip = (long)SvIV(ST(5));
	}

	if (items < 7)
	    numToReturn = -1;
	else {
	    numToReturn = (long)SvIV(ST(6));
	}

	if (items < 8)
	    flag = 0;
	else {
	    flag = (int)SvIV(ST(7));
	}

	if (items < 9)
	    optionsv = NULL;
	else {
	    optionsv = ST(8);
	}

	RETVAL = THIS->explain(conditionsv, selectorsv, orderbysv, hintsv, numToSkip, numToReturn, flag, optionsv);
	ST(0) = sv_newmortal();
   sv_setref_pv(ST(0), "SequoiaDB::Cursor", (void *) RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_update); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_update)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "THIS, rulesv, conditionsv, hintsv");
    {
	SV *	rulesv = ST(1);
	SV *	conditionsv = ST(2);
	SV *	hintsv = ST(3);
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	bool	RETVAL;

	RETVAL = THIS->update(rulesv, conditionsv, hintsv);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_upsert); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_upsert)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "THIS, rulesv, conditionsv, hintsv");
    {
	SV *	rulesv = ST(1);
	SV *	conditionsv = ST(2);
	SV *	hintsv = ST(3);
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	bool	RETVAL;

	RETVAL = THIS->upsert(rulesv, conditionsv, hintsv);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_createIndex); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_createIndex)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 3 || items > 5)
       croak_xs_usage(cv,  "THIS, indexName, conditionsv, isUniquesv = NULL, enforcedsv = NULL");
    {
	const char *	indexName = (const char *)SvPV_nolen(ST(1));
	SV *	conditionsv = ST(2);
	SV *	isUniquesv;
	SV *	enforcedsv;
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	bool	RETVAL;

	if (items < 4)
	    isUniquesv = NULL;
	else {
	    isUniquesv = ST(3);
	}

	if (items < 5)
	    enforcedsv = NULL;
	else {
	    enforcedsv = ST(4);
	}

	RETVAL = THIS->createIndex(indexName, conditionsv, isUniquesv, enforcedsv);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_listIndexes); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_listIndexes)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "THIS, indexName = \"\"");
    {
	const char *	indexName;
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	plCursor *	RETVAL;

	if (items < 2)
	    indexName = "";
	else {
	    indexName = (const char *)SvPV_nolen(ST(1));
	}

	RETVAL = THIS->listIndexes(indexName);
	ST(0) = sv_newmortal();
   sv_setref_pv(ST(0), "SequoiaDB::Cursor", (void *) RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_remove)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "THIS, conditionsv, hintsv = NULL");
    {
	SV *	conditionsv = ST(1);
	SV *	hintsv;
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	bool	RETVAL;

	if (items < 3)
	    hintsv = NULL;
	else {
	    hintsv = ST(2);
	}

	RETVAL = THIS->remove(conditionsv, hintsv);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_split); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_split)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 4 || items > 5)
       croak_xs_usage(cv,  "THIS, sourceGroup, targetGroup, conditionsv, staticsv = NULL");
    {
	const char *	sourceGroup = (const char *)SvPV_nolen(ST(1));
	const char *	targetGroup = (const char *)SvPV_nolen(ST(2));
	SV *	conditionsv = ST(3);
	SV *	staticsv;
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	bool	RETVAL;

	if (items < 5)
	    staticsv = NULL;
	else {
	    staticsv = ST(4);
	}

	RETVAL = THIS->split(sourceGroup, targetGroup, conditionsv, staticsv);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_splitAsync); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_splitAsync)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 4 || items > 5)
       croak_xs_usage(cv,  "THIS, sourceGroup, targetGroup, conditionsv, staticsv = NULL");
    {
	const char *	sourceGroup = (const char *)SvPV_nolen(ST(1));
	const char *	targetGroup = (const char *)SvPV_nolen(ST(2));
	SV *	conditionsv = ST(3);
	SV *	staticsv;
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	long	RETVAL;
	dXSTARG;

	if (items < 5)
	    staticsv = NULL;
	else {
	    staticsv = ST(4);
	}

	RETVAL = THIS->splitAsync(sourceGroup, targetGroup, conditionsv, staticsv);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_alterCollection); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_alterCollection)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, sv");
    {
	SV *	sv = ST(1);
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	bool	RETVAL;

	RETVAL = THIS->alterCollection(sv);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_attachCollection); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_attachCollection)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "THIS, sdbFullName, sv");
    {
	const char *	sdbFullName = (const char *)SvPV_nolen(ST(1));
	SV *	sv = ST(2);
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	bool	RETVAL;

	RETVAL = THIS->attachCollection(sdbFullName, sv);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_detachCollection); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_detachCollection)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, sdbFullName");
    {
	const char *	sdbFullName = (const char *)SvPV_nolen(ST(1));
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	bool	RETVAL;

	RETVAL = THIS->detachCollection(sdbFullName);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_aggregate); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_aggregate)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, sv");
    {
	SV *	sv = ST(1);
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));
	plCursor *	RETVAL;

	RETVAL = THIS->aggregate(sv);
	ST(0) = sv_newmortal();
   sv_setref_pv(ST(0), "SequoiaDB::Cursor", (void *) RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__Collection_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__Collection_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	plCollection *   THIS = (plCollection *) SvIV((SV*) SvRV(ST(0)));

	delete THIS;
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_SequoiaDB__Collection); /* prototype to pass -Wmissing-prototypes */
XS(boot_SequoiaDB__Collection)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        newXS("SequoiaDB::Collection::new", XS_SequoiaDB__Collection_new, file);
        newXS("SequoiaDB::Collection::query", XS_SequoiaDB__Collection_query, file);
        newXS("SequoiaDB::Collection::insert", XS_SequoiaDB__Collection_insert, file);
        newXS("SequoiaDB::Collection::bulkInsert", XS_SequoiaDB__Collection_bulkInsert, file);
        newXS("SequoiaDB::Collection::count", XS_SequoiaDB__Collection_count, file);
        newXS("SequoiaDB::Collection::getCLName", XS_SequoiaDB__Collection_getCLName, file);
        newXS("SequoiaDB::Collection::getCSName", XS_SequoiaDB__Collection_getCSName, file);
        newXS("SequoiaDB::Collection::getFullName", XS_SequoiaDB__Collection_getFullName, file);
        newXS("SequoiaDB::Collection::createLob", XS_SequoiaDB__Collection_createLob, file);
        newXS("SequoiaDB::Collection::removeLob", XS_SequoiaDB__Collection_removeLob, file);
        newXS("SequoiaDB::Collection::openLob", XS_SequoiaDB__Collection_openLob, file);
        newXS("SequoiaDB::Collection::listLobs", XS_SequoiaDB__Collection_listLobs, file);
        newXS("SequoiaDB::Collection::explain", XS_SequoiaDB__Collection_explain, file);
        newXS("SequoiaDB::Collection::update", XS_SequoiaDB__Collection_update, file);
        newXS("SequoiaDB::Collection::upsert", XS_SequoiaDB__Collection_upsert, file);
        newXS("SequoiaDB::Collection::createIndex", XS_SequoiaDB__Collection_createIndex, file);
        newXS("SequoiaDB::Collection::listIndexes", XS_SequoiaDB__Collection_listIndexes, file);
        newXS("SequoiaDB::Collection::remove", XS_SequoiaDB__Collection_remove, file);
        newXS("SequoiaDB::Collection::split", XS_SequoiaDB__Collection_split, file);
        newXS("SequoiaDB::Collection::splitAsync", XS_SequoiaDB__Collection_splitAsync, file);
        newXS("SequoiaDB::Collection::alterCollection", XS_SequoiaDB__Collection_alterCollection, file);
        newXS("SequoiaDB::Collection::attachCollection", XS_SequoiaDB__Collection_attachCollection, file);
        newXS("SequoiaDB::Collection::detachCollection", XS_SequoiaDB__Collection_detachCollection, file);
        newXS("SequoiaDB::Collection::aggregate", XS_SequoiaDB__Collection_aggregate, file);
        newXS("SequoiaDB::Collection::DESTROY", XS_SequoiaDB__Collection_DESTROY, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

