/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of BSON.xs. Do not edit this file, edit BSON.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "BSON.xs"
#ifdef __cplusplus
extern "C"{
#endif

#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#ifdef __cplusplus
}
#endif

#include "ppport.h"

#include "plBSONObj.hpp"

using namespace std;
using namespace sdbclient ;
using namespace bson ;

#line 32 "BSON.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 84 "BSON.c"

XS(XS_SequoiaDB__BSON_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__BSON_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "CLASS, sv=NULL");
    {
	SV *	sv;
	char *	CLASS = (char *)SvPV_nolen(ST(0));
	plBSONObj *	RETVAL;

	if (items < 2)
	    sv = NULL;
	else {
	    sv = ST(1);
	}

	RETVAL = new plBSONObj(sv);
	ST(0) = sv_newmortal();
   sv_setref_pv(ST(0), CLASS, (void *) RETVAL);

    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__BSON_toString); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__BSON_toString)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	plBSONObj *   THIS = (plBSONObj *) SvIV((SV*) SvRV(ST(0)));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = THIS->toString();
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__BSON_get); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__BSON_get)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, key");
    {
	const char *	key = (const char *)SvPV_nolen(ST(1));
	plBSONObj *   THIS = (plBSONObj *) SvIV((SV*) SvRV(ST(0)));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = THIS->get(key);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__BSON_put); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__BSON_put)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "THIS, key, value");
    {
	const char *	key = (const char *)SvPV_nolen(ST(1));
	const char *	value = (const char *)SvPV_nolen(ST(2));
	plBSONObj *   THIS = (plBSONObj *) SvIV((SV*) SvRV(ST(0)));
	bool	RETVAL;

	RETVAL = THIS->put(key, value);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__BSON_toBson); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__BSON_toBson)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, sv");
    {
	SV *	sv = ST(1);
	plBSONObj *   THIS = (plBSONObj *) SvIV((SV*) SvRV(ST(0)));
	int	RETVAL;
	dXSTARG;

	RETVAL = THIS->toBson(sv);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__BSON_toBson2); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__BSON_toBson2)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, sv");
    {
	SV *	sv = ST(1);
	plBSONObj *   THIS = (plBSONObj *) SvIV((SV*) SvRV(ST(0)));
	int	RETVAL;
	dXSTARG;

	RETVAL = THIS->toBson2(sv);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__BSON_getBson); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__BSON_getBson)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, sv");
    {
	SV *	sv = ST(1);
	plBSONObj *   THIS = (plBSONObj *) SvIV((SV*) SvRV(ST(0)));
	SV *	RETVAL;

	RETVAL = THIS->getBson(sv);
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__BSON_toString2); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__BSON_toString2)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	plBSONObj *   THIS = (plBSONObj *) SvIV((SV*) SvRV(ST(0)));
	SV *	RETVAL;

	RETVAL = THIS->toString2();
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_SequoiaDB__BSON_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_SequoiaDB__BSON_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	plBSONObj *   THIS = (plBSONObj *) SvIV((SV*) SvRV(ST(0)));

	delete THIS;
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_SequoiaDB__BSON); /* prototype to pass -Wmissing-prototypes */
XS(boot_SequoiaDB__BSON)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        newXS("SequoiaDB::BSON::new", XS_SequoiaDB__BSON_new, file);
        newXS("SequoiaDB::BSON::toString", XS_SequoiaDB__BSON_toString, file);
        newXS("SequoiaDB::BSON::get", XS_SequoiaDB__BSON_get, file);
        newXS("SequoiaDB::BSON::put", XS_SequoiaDB__BSON_put, file);
        newXS("SequoiaDB::BSON::toBson", XS_SequoiaDB__BSON_toBson, file);
        newXS("SequoiaDB::BSON::toBson2", XS_SequoiaDB__BSON_toBson2, file);
        newXS("SequoiaDB::BSON::getBson", XS_SequoiaDB__BSON_getBson, file);
        newXS("SequoiaDB::BSON::toString2", XS_SequoiaDB__BSON_toString2, file);
        newXS("SequoiaDB::BSON::DESTROY", XS_SequoiaDB__BSON_DESTROY, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

